### Приветствие
GET http://localhost:8080/calculator

### Сумма
GET http://localhost:8080/calculator/plus?num1=5&num2=5

### Вычитание
GET http://localhost:8080/calculator/minus?num1=5&num2=5

### Умножение
GET http://localhost:8080/calculator/multiply?num1=5&num2=5

### Деление
GET http://localhost:8080/calculator/divide?num1=5&num2=5

### Деление на 0
GET http://localhost:8080/calculator/divide?num1=5&num2=0

### Не введены числа
GET http://localhost:8080/calculator/plus
